### ISSUE TITLE
Please add the DOI of the new publication to the README

### ISSUE THREAD

**Issue by draeger** [draeger-lab/refinegems#100]
A publication that covers the primary features of this project just came out, see https://doi.org/10.3389/fbinf.2023.1214074. It would be good to add it prominently to the README file, possibly in addition to the ZENODO link as a badge.

- [x] Badge in README for publication in Frontiers
- [x] Include 'How to cite' in README
- [x] Include 'How to cite' in documentation
- [x] Add CITATION.cff
- [x] Change setup.py to pyproject.toml for new release
- [ ] Fix python version badge in README -> Might already be correct. Needs to be pushed to `main` to test it.

**Comment by GwennyGit** [comment]
I added a badge for the publication in Frontiers to the README and changed the badge for the Zenodo DOI. This badge was changed for two reasons: (a) the design is now the same for both DOI badges and, more importantly, (b) to reduce confusion as the label of the Zenodo DOI badge was only DOI. These changes are currently only on the development branch `dev`. The reasoning is that the README shown in PyPI is only updated if a new release is made. Thus, adding the new badge in the README on the main branch makes only sense with a new release.

@cb-Hades and @f3rryman, we should see if the changes currently on `dev` would already be enough for a tiny release to add the README changes. Maybe we can turn the setup.py into the pyproject.toml and use this as a reason for a new release? 🤔
