### ISSUE TITLE
Release a version 1.4.3 with deprecation warnings

### ISSUE THREAD

**Issue by GwennyGit** [draeger-lab/refinegems#130]
As we started working towards a version 2.0.0 with refactored code and new functionalities, we started removing functions and rewriting complete modules. Thus, to warn the users before we release version 2.0.0, we should release version 1.4.3 with deprecation warnings.

Also, we should print a warning e.g. when loading the module about the restructuring.

Problem: 

Basically all functions are know either moved to a new location, renamed or deleted due to the restructuring.

Current setup:

- FutureWarning and Deprecation warning by module import (for each module) with hint where to find them from version 2.0.0 onwards
- also added the deprecation warning to the docstrings

**Comment by cb-Hades** [comment]
Merged into main #132 

Published as version 1.5.0.
