### ISSUE TITLE
Implement functionality to work with multiple databases

### ISSUE THREAD

**Issue by famosab** [draeger-lab/refinegems#43]
**Is your feature request related to a problem? Please describe.**
Multiple databases like KEGG and BiGG are referenced and used within refineGEMs but sometimes functions overlap or duplicate and the databases are not updated.

**Describe the solution you'd like**
Something triggered by the user which leads to a one-time download (the MCC tool does that) which can be reused or updated. 

Maybe this can be bundled into a submodule `databases.py` which takes care of downloading and then parsing as well as formatting so that these databases can be used by a refineGEMs user and within the scripts provided by refineGEMs. (see #31, #28)

**Comment by GwennyGit** [comment]
As the main aim of this issue, namely downloading and maintaining the different databases used within refineGEMs in one place, is already implemented, this issue can be closed. Furthermore, enhancing refineGEMs through the usage of more databases is already handled or mentioned in more detail in issue #36, and the storage question of these databases is already mentioned in more detail in issue #49. Thus, I will close this issue as completed.
