### ISSUE TITLE
Implement parsing of different formats

### ISSUE THREAD

**Issue by famosab** [draeger-lab/refinegems#44]
So far only `.xml` can be used with refineGEMs. Other fileformats are also being used like `.yml`. It might be of interest to enable other formats or even an automated choice of parser so that a user can simply plug-and-play.

- [x] Add functionality with cobraPy
- [x] Add functionality with libSBML

**Comment by cb-Hades** [comment]
`load_model_cobra` in `io.py` can now read in any format that is readable by COBRApy 
-> model is read in based on the file extension

**Comment by cb-Hades** [comment]
All four frequently used model formats - XML, YAML, MatLab, JSON - can now be used as input and output formats for the load/write model function - independently of whether the model was loaded with COBRApy or libSBML.
