### ISSUE TITLE
Store all necessary data in `data`

### ISSUE THREAD

**Issue by GwennyGit** [draeger-lab/refinegems#49]
**Feature request**
As refineGEMs already has a database to store the SBO annotation tables for the module `SBO annotation`, the idea would be to expand this database to also contain files necessary for other modules. Thus, reducing the accumulation of files, due to all files necessary for the modules being stored in one place. <br>
As @famosab already suggested creating a submodule `database.py` in issue #43, this module could also be used to initialise and load the internal refineGEMs database. 
***
**Required steps:**
- [x] Rename database to e.g. `data`
- [x] Create `databases.py`
`databases.py` should contain the following functions:
  - [x] Initialise database
  - [x] Is database valid
  - [x] Load database
- [x] Refactor code in the modules:
  - [x] `modelseed`
  - [x] `growth`
  - [x] `gapfill`
- [x] Add following new functions to `io`:
  - [x] Adds new medium to `data` -> For development/maintenance
  - [x] Extracts all media/a user-specified medium with their respective composition(s) as TSV/CSV file from `data`
  - [x] Add function for easier extension of the database with new columns/entries (e.g. to add identifiers from other databases) -> For development/maintenance
  - [x] Function to use user-defined medium -> `load_medium_custom` could be changed or left as is? 🤔 
- [x] Change code in `growth.py` to use either user-specified medium/medium from `data.db`? 🤔  
- [x] Extend the media-related tables
  - [x] Change the name of the table `media` to `medium` & change column name `medium` to `name`
    - [x] Add column `reference`
    - [x] Fill column `reference`
  - [x] Add the table `substance` -> Contains the columns `id | substance | formula`
    - [x] Fill the column `formula`
    - [x] Change substance names to one name per substance
  - [x] Add the table `substance2db` -> Contains the columns `substance_id | db_id | db_type`
        -> More rows for more identifier namespaces can be added 
  - [x] Add SEED identifiers
  - [x] Change the name of the table `media_compositions` to `medium2substance` & rearrange to fit to the other media-related tables
    - [x] Remove the columns `BiGG` & `substance`
    - [x] Move column `medium_id` to be the first column
    - [x] Change column `substance_id` to refer to the `id` in `substance` & move to the second column
    - [x] Additionally, add column `flux` to enable growth analyses with per medium-defined fluxes 
    - [x] Fill flux column so far possible ${\rightarrow \text{\textcolor{orange}{Growth\ analyses\ should\ still\ be\ able\ to\ run\ with\ a\ default\ mode\ if\ column\ 'flux'\ is\ empty!}}}$
    - [x] Additionally, add column `origin` to link the substances to their medium-specific names/derived from compound names
    - [x] Rename column `origin` to `source`
    - [x] Fill column `source`

**Comment by GwennyGit** [comment]
All commits multiplicated commits since the last comment are the result of my attempt to rebase these commits from `dev` to another branch. However, this did not work and, thus, I will cherry-pick the according commits to the other branch. This will likely add the same commits again in this issue after this comment.

**Comment by GwennyGit** [comment]
Removed H3BO3 from the `substance2db` table. -> No BiGG, KEGG or SEED identifier found.

**Comment by GwennyGit** [comment]
I removed all entries for the substances `EDTA`, `Phenol Red`, `Resazurin` and `H3BO3`. These substances seem not to affect growth but are only needed for lab researchers.

`2,2-Bipyridine` remains for now disconnected in the `medium2substance` table as I was unsure whether to remove it.

**Comment by GwennyGit** [comment]
@NantiaL provided the full flux table for the medium ‘Blood’ as the version from the paper [‘New workflow predicts drug targets against sars-cov-2 via metabolic changes in infected cells’](https://doi.org/10.1371/journal.pcbi.1010903) only contains the fluxes and metabolites of the medium ‘Blood’ relevant for the study.

In the case of `L-Cysteine` and `L-Cystine` the identifiers were incorrect, and, thus, the flux could not be mapped according to the identifier. In this case, I mapped the fluxes according to the provided full name. 
For the case of `Sorbitol` we have currently an identifier for `L-Sorbitol` and one for `D-Sorbitol`. Hence, I mapped the flux for `Sorbitol` to both of the identifiers. 
All other identifiers and full names could be directly mapped to exactly one identifier already in the database.

**Comment by cb-Hades** [comment]
In/Out functions for the database should work now, @GwennyGit . 

Additionally, `format_substance_table` was added to allow reformatting of the substance table. The format `growth_old` is a first try to create a table that works with the current growth module, but has yet to be tested. 

To produce an entry for the documentation, I would suggest using the 'documentation' type in `load_substance_table_from_db`, but that is currently only an idea.

**Comment by cb-Hades** [comment]
Added a writer fro rst table for the medium table to the medium class, which can new be called by using export_to_file with the type rst or docs.

@GwennyGit  - please check if the table is how you wanted it and if the default sizes are fitting or should be adjusted.

**Comment by GwennyGit** [comment]
All listed tasks are done — closing issue.
